version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/coupang_rank
      - REDIS_URL=redis://redis:6379/0
      - DISPLAY=:0
    volumes:
      - ./backend/src:/app/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./shared_tmp:/tmp
    depends_on:
      - db
      - redis

  celery_worker:
    build: ./backend
    command: celery -A src.worker.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/coupang_rank
      - REDIS_URL=redis://redis:6379/0
      - DISPLAY=:0
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - backend
      - redis

  celery_flower:
    build: ./backend
    command: celery -A src.worker.celery flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - celery_worker

  celery_beat:
    build: ./backend
    command: celery -A src.worker.celery beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/coupang_rank
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=coupang_rank
    volumes:
      - postgres_data:/var/lib/postgresql/data

  crawler:
    build:
      context: .
      dockerfile: crawler/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DISPLAY=:0
    volumes:
      - ./shared_tmp:/tmp

volumes:
  postgres_data: